"""English soccer team names → 国内常用中文名。查不到就原样返回。"""

TEAM_ZH = {
    # 英超
    "Arsenal": "阿森纳",
    "Aston Villa": "阿斯顿维拉",
    "AFC Bournemouth": "伯恩茅斯",
    "Bournemouth": "伯恩茅斯",
    "Brentford": "布伦特福德",
    "Brighton": "布莱顿",
    "Brighton & Hove Albion": "布莱顿",
    "Chelsea": "切尔西",
    "Crystal Palace": "水晶宫",
    "C Palace": "水晶宫",
    "Everton": "埃弗顿",
    "Fulham": "富勒姆",
    "Ipswich": "伊普斯维奇",
    "Ipswich Town": "伊普斯维奇",
    "Leeds": "利兹联",
    "Leeds United": "利兹联",
    "Liverpool": "利物浦",
    "Manchester City": "曼城",
    "Man City": "曼城",
    "Manchester United": "曼联",
    "Man United": "曼联",
    "Man Utd": "曼联",
    "Newcastle": "纽卡斯尔",
    "Newcastle United": "纽卡斯尔",
    "Nottingham Forest": "诺丁汉森林",
    "Nottm Forest": "诺丁汉森林",
    "Sunderland": "桑德兰",
    "Tottenham Hotspur": "热刺",
    "Spurs": "热刺",
    "West Ham": "西汉姆",
    "West Ham United": "西汉姆",
    "Wolves": "狼队",
    "Wolverhampton Wanderers": "狼队",
    "Coventry": "考文垂",
    "Coventry City": "考文垂",
    "Hull": "赫尔城",
    "Hull City": "赫尔城",
    "Leicester": "莱斯特城",
    "Leicester City": "莱斯特城",
    "Southampton": "南安普顿",
    "Burnley": "伯恩利",
    # 西甲
    "Alavés": "阿拉维斯",
    "Athletic": "毕尔巴鄂",
    "Athletic Club": "毕尔巴鄂",
    "Atlético": "马竞",
    "Atlético Madrid": "马竞",
    "Atletico Madrid": "马竞",
    "Atletico": "马竞",
    "Barcelona": "巴萨",
    "FC Barcelona": "巴萨",
    "Celta Vigo": "塞尔塔",
    "Deportivo": "拉科鲁尼亚",
    "Elche": "埃尔切",
    "Espanyol": "西班牙人",
    "Getafe": "赫塔费",
    "Girona": "赫罗纳",
    "Levante": "莱万特",
    "Mallorca": "马略卡",
    "Málaga": "马拉加",
    "Osasuna": "奥萨苏纳",
    "Rayo": "巴列卡诺",
    "Rayo Vallecano": "巴列卡诺",
    "Real Betis": "贝蒂斯",
    "Betis": "贝蒂斯",
    "Real Madrid": "皇马",
    "Real Sociedad": "皇家社会",
    "Sevilla": "塞维利亚",
    "Valencia": "瓦伦西亚",
    "Villarreal": "比利亚雷亚尔",
    "Racing": "桑坦德竞技",
    "Racing Santander": "桑坦德竞技",
    # 德甲
    "Bayern": "拜仁",
    "Bayern Munich": "拜仁",
    "FC Bayern Munich": "拜仁",
    "FC Bayern München": "拜仁",
    "Bayern München": "拜仁",
    "Bayer Leverkusen": "勒沃库森",
    "Leverkusen": "勒沃库森",
    "Borussia Dortmund": "多特蒙德",
    "Dortmund": "多特蒙德",
    "RB Leipzig": "莱比锡",
    "Eintracht Frankfurt": "法兰克福",
    "Frankfurt": "法兰克福",
    "Borussia Mönchengladbach": "门兴",
    "Gladbach": "门兴",
    "VfB Stuttgart": "斯图加特",
    "Stuttgart": "斯图加特",
    "SC Freiburg": "弗赖堡",
    "Freiburg": "弗赖堡",
    "Werder Bremen": "不莱梅",
    "Bremen": "不莱梅",
    "TSG Hoffenheim": "霍芬海姆",
    "Hoffenheim": "霍芬海姆",
    "1. FC Union Berlin": "柏林联合",
    "Union Berlin": "柏林联合",
    "FC Cologne": "科隆",
    "Cologne": "科隆",
    "Mainz": "美因茨",
    "FC Augsburg": "奥格斯堡",
    "Augsburg": "奥格斯堡",
    "Hamburg": "汉堡",
    "Hamburg SV": "汉堡",
    "Schalke": "沙尔克",
    "Schalke 04": "沙尔克",
    "SC Paderborn 07": "帕德博恩",
    "Paderborn": "帕德博恩",
    "SV ELVERSBERG": "埃尔弗斯贝格",
    "ELVERSBERG": "埃尔弗斯贝格",
    "Heidenheim": "海登海姆",
    "Wolfsburg": "沃尔夫斯堡",
    "St. Pauli": "圣保利",
    # 意甲
    "Inter Milan": "国米",
    "Internazionale": "国米",
    "FC Internazionale Milano": "国米",
    "Inter": "国米",
    "AC Milan": "AC米兰",
    "Milan": "AC米兰",
    "Juventus": "尤文图斯",
    "Napoli": "那不勒斯",
    "AS Roma": "罗马",
    "Roma": "罗马",
    "Lazio": "拉齐奥",
    "Atalanta": "亚特兰大",
    "Fiorentina": "佛罗伦萨",
    "Bologna": "博洛尼亚",
    "Torino": "都灵",
    "Udinese": "乌迪内斯",
    "Genoa": "热那亚",
    "Cagliari": "卡利亚里",
    "Como": "科莫",
    "Lecce": "莱切",
    "Parma": "帕尔马",
    "Monza": "蒙扎",
    "Sassuolo": "萨索洛",
    "Venezia": "威尼斯",
    "Frosinone": "弗罗西诺内",
    "Hellas Verona": "维罗纳",
    "Empoli": "恩波利",
    # 法甲
    "Paris Saint-Germain": "巴黎圣日耳曼",
    "Paris Saint Germain": "巴黎圣日耳曼",
    "Paris SG": "巴黎圣日耳曼",
    "PSG": "巴黎圣日耳曼",
    "Monaco": "摩纳哥",
    "AS Monaco": "摩纳哥",
    "Marseille": "马赛",
    "Lyon": "里昂",
    "Lille": "里尔",
    "Nice": "尼斯",
    "Lens": "朗斯",
    "Rennes": "雷恩",
    "Stade Rennais": "雷恩",
    "Strasbourg": "斯特拉斯堡",
    "Toulouse": "图卢兹",
    "Brest": "布雷斯特",
    "Nantes": "南特",
    "Reims": "兰斯",
    "Montpellier": "蒙彼利埃",
    "Angers": "昂热",
    "AJ Auxerre": "欧塞尔",
    "Auxerre": "欧塞尔",
    "Le Havre AC": "勒阿弗尔",
    "Lorient": "洛里昂",
    "Troyes": "特鲁瓦",
    "Paris FC": "巴黎FC",
    "Le Mans": "勒芒",
}


def zh_team(name: str | None) -> str:
    if not name:
        return ""
    text = name.strip()
    return TEAM_ZH.get(text, text)
